version: "3.8"

services:
 db:
  image: postgres:latest
  environment:
   POSTGRES_DB: blogapp
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgrespw
  ports:
   - "5432:5432"
  volumes:
   - db_data:/var/lib/postgresql/data

 api:
  image: lionheartt4/blogapp:latest
  build:
   context: .
  ports:
   - "8080:80"
  environment:
   - ASPNETCORE_ENVIRONMENT=Production
   - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=blogapp;Username=postgres;Password=postgrespw
  depends_on:
   - db

volumes:
 db_data:
