version: "3.8"

services:
 postgres:
  image: postgres:13
  environment:
   POSTGRES_USER: yourusername
   POSTGRES_PASSWORD: yourpassword
   POSTGRES_DB: blogapp
  ports:
   - "5432:5432"
  volumes:
   - postgres-data:/var/lib/postgresql/data

 api:
  image: your-api-image
  environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=blogapp;Username=yourusername;Password=yourpassword
  depends_on:
   - postgres
  ports:
   - "5000:80"
  networks:
   - backend

volumes:
 postgres-data:

networks:
 backend:
