version: "3.8"

services:
 api:
  image: mcr.microsoft.com/dotnet/aspnet:6.0
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "80:80"
  environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=blogapp;Username=postgres;Password=postgrespw
  depends_on:
   - postgres

 postgres:
  image: postgres:latest
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgrespw
   POSTGRES_DB: blogapp
  ports:
   - "5432:5432"
  volumes:
   - pgdata:/var/lib/postgresql/data

volumes:
 pgdata:
